Update wallpaper

diff --git a/wallpaper b/wallpaper
--- a/wallpaper
+++ b/wallpaper
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
-# Author: Daniel Neemann
+# author: daniel neemann (@zzzeyez)
+#
+# sets wallpaper from `wal` color number,
+# image address or hex value
+#
+#
 
 . "$HOME/.cache/wal/colors.sh"
 
@@ -11,24 +16,22 @@ wallpaper 5
 wallpaper ./smiledog.jpg
 wallpaper dddddd"
 
-set_wallpaper(){
-    # osascript is up to Mountain Lion (10.8.5)
-    # the next version of mountain lion is Mavericks (10.9)
-    METHOD=$(sw_vers -productVersion | awk -F'.' '{ if ($1 < 10 || $2 < 9) { print "osascript" } else{ print "sqlite3"  } }')
-    case $METHOD in
+set_wallpaper() {
+	METHOD=$(sw_vers -productVersion | awk -F'.' '{ if ($1 < 10 || $2 < 9) { print "osascript" } else{ print "sqlite3"  } }')
+	case $METHOD in
         osascript)
-            osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"${1}\""
-            ;;
-        sqlite3)
-            current_path=$(sqlite3 -noheader -batch ${HOME}/Library/Application\ Support/Dock/desktoppicture.db 'select value from data limit 1')
-            if [[ "$current_path" != "$1" ]]; then
-                sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}'" && killall Dock
-            fi
-            ;;
-        *)
-            echo "I can't set the wallpaper" && exit 1
-            ;;
-    esac
+		osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"${1}\""
+	;;
+	sqlite3)
+		current_path=$(sqlite3 -noheader -batch ${HOME}/Library/Application\ Support/Dock/desktoppicture.db 'select value from data limit 1')
+		if [[ "$current_path" != "$1" ]]; then
+			sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}'" && killall Dock
+		fi
+	;;
+	*)
+		echo "error setting wallpaper" && exit 1
+	;;
+	esac
 }
 
 case "$1" in
