new scripts

diff --git a/wallpaper b/wallpaper
--- a/wallpaper
+++ b/wallpaper
@@ -11,6 +11,26 @@ wallpaper 5
 wallpaper ./smiledog.jpg
 wallpaper dddddd"
 
+set_wallpaper(){
+    # osascript is up to Mountain Lion (10.8.5)
+    # the next version of mountain lion is Mavericks (10.9)
+    METHOD=$(sw_vers -productVersion | awk -F'.' '{ if ($1 < 10 || $2 < 9) { print "osascript" } else{ print "sqlite3"  } }')
+    case $METHOD in
+        osascript)
+            osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"${1}\""
+            ;;
+        sqlite3)
+            current_path=$(sqlite3 -noheader -batch ${HOME}/Library/Application\ Support/Dock/desktoppicture.db 'select value from data limit 1')
+            if [[ "$current_path" != "$1" ]]; then
+                sqlite3 ${HOME}/Library/Application\ Support/Dock/desktoppicture.db "update data set value = '${1}'" && killall Dock
+            fi
+            ;;
+        *)
+            echo "I can't set the wallpaper" && exit 1
+            ;;
+    esac
+}
+
 case "$1" in
 
 	-h|-H|--help) echo "$help" && exit ;;
@@ -32,5 +52,6 @@ esac
 # osascript does not allow you to repeatedly set as same image
 # so we generate an additional image
 convert -size 5x5 xc:"$color0" "$image2" &&
-osascript -e 'tell application "Finder" to set desktop picture to POSIX file "'$image2'"' &&
-osascript -e 'tell application "Finder" to set desktop picture to POSIX file "'$image'"'
+set_wallpaper "$image2" &&
+set_wallpaper "$image"
+
